### ISSUE TITLE
Login issue with redirect uri

### ISSUE THREAD

**Issue by Avishaidev** [andreaolivato/TikTok-LoginKit-PHP#1]
I confugre all details as needed but can't login using your php sdk.
What am i missing??? Please help.

PHP login code:
![login tiktok code](https://user-images.githubusercontent.com/24667354/152488099-dd9bc7c3-273c-4574-b83d-221844c84a19.png)

Tiktok app details:
![tiktok app details](https://user-images.githubusercontent.com/24667354/152488147-065325ad-117e-4996-a7b5-956af63af80b.png)

Login Error:
![tiktok error](https://user-images.githubusercontent.com/24667354/152488172-1a15bda5-1ed4-4abf-99ba-88a536b851ed.png)

**Comment by ley-288** [comment]
Same issue, Did you resolve this error?

**Comment by Avishaidev** [comment]
Yes  my issue was because i used sub domain

**Comment by VinceSanityyy** [comment]
Is it possible to try this in localhost with ngrok? I got the same problem
