### ISSUE TITLE
Invalid Chunk Size

### ISSUE THREAD

**Issue by ZekiJohn** [andreaolivato/TikTok-LoginKit-PHP#11]
Hi

I'm using VideoFromFile, and I'm getting this error.

TikTok Api Error, invalid Upload. Error: invalid_params - The chunk size is invalid

It's functioning properly for other clips; the issue is only with this particular video, which isn't even longer than the ones already uploaded.

Thx

**Comment by andreaolivato** [comment]
Hi there,

The error is from the TikTok API themselves. If you want, upload the video here and I can take a look
