### ISSUE TITLE
Scope error

### ISSUE THREAD

**Issue by Eisbaeeer** [andreaolivato/TikTok-LoginKit-PHP#12]
Hi.
I tried to use the loginkit. The app is approved. After logging in, I run into "scope" error.
Where can I define the scopes?

I used the example login script with this URL: https://counter.kidbuild.de/tiktok.php

This url is the redirect url, too.

![image](https://github.com/andreaolivato/TikTok-LoginKit-PHP/assets/4928271/baf74c44-550c-4086-b20e-ecc84bddadf8)

![image](https://github.com/andreaolivato/TikTok-LoginKit-PHP/assets/4928271/e666a3ee-31af-4aa9-8ea4-e3907272c9a8)

My target is to get the follower counts of user.
Greets Lars

**Comment by andreaolivato** [comment]
Hi there,

Not experiencing this using a different `client_key` so there must be an error on your client key or your app might not be fully active.

I've copied the same auth_url from your example, changed the `client_key` and `redirect_uri` and it worked correctly... so must be some missing auth/activation on the TikTok developer panel

**Comment by andreaolivato** [comment]
Remove the 'video.list' scope, you don't have that approved

**Comment by andreaolivato** [comment]
`$_TK->getRedirect([TikTokLoginKit\Connector::PERMISSION_USER_BASIC]);`

**Comment by Eisbaeeer** [comment]
Thank you for your support!

**Comment by Eisbaeeer** [comment]
Additional question. I added scope "TikTokLoginKit\Connector::PERMISSION_USER_STATS" to get the followers count. But still showing no followers.
Code
```
if (TikTokLoginKit\Connector::receivingResponse()) { // Check if you're receiving the Authorisation Code
	try {
		$token = $_TK->verifyCode($_GET[TikTokLoginKit\Connector::CODE_PARAM]); // Verify the Authorisation code and get the Access Token

		/****  Your logic to store the access token goes here ****/

		$user = $_TK->getUser(); // Retrieve the User Object

		/****  Your logic to store or use the User Info goes here ****/

		//$userinfo = $_TK->getUserInfo(); // Retrieve the Userinfo Object

		/****  Your logic to store or use the Video Info goes here ****/

		// Print some HTML as example
		echo <<<HTML
			<h2>User Info</h2>
			<table width="400">
				<tr>
					<td with="100"><img src="{$user->getBestAvatar()}" style="width:100%"></td>
					<td with="700">
						<br />
						<strong>ID</strong>: {$user->getOpenID()}<br /><br />
						<strong>UnionID</strong>: {$user->getUnionID()}<br /><br />
						<strong>Name</strong>: {$user->getDisplayName()}<br /><br />
						<strong>Followers</strong>: {$user->getFollowers()}<br /><br />
						<strong>Following</strong>: {$user->getFollowing()}<br /><br />
						<strong>Bio</strong>: {$user->getBio()}<br /><br />
						<strong>Likes</strong>: {$user->getLikes()}<br /><br />
						<strong>Videos</strong>: {$user->getNumVideos()}<br /><br />
					</td>
				</tr>
			</table>
		HTML;
		
	} catch (Exception $e) {
		echo "Error: ".$e->getMessage();
		echo '<br /><a href="?">Retry</a>';
	}
} else { // Print the initial login button that redirects to TikTok
	echo '<a href="'.$_TK->getRedirect([TikTokLoginKit\Connector::PERMISSION_USER_BASIC, TikTokLoginKit\Connector::PERMISSION_USER_STATS]).'">Log in with TikTok</a>';
}
?>
```

![image](https://github.com/andreaolivato/TikTok-LoginKit-PHP/assets/4928271/b392ca86-d7c0-47c6-a88d-81d2accb21cc)

**Comment by andreaolivato** [comment]
Your code is missing requesting for specific fields.

When you call the `getUser` function, you need to specify which fields you want returned, otherwise you only get the standard ones.

For example

```
$_TK->getUser([Connector::FIELD_U_FOLLOWERS, Connector::FIELD_U_FOLLOWING]);
```

This returns followers and following.
