### ISSUE TITLE
Scopes question user.info.*

### ISSUE THREAD

**Issue by Eisbaeeer** [andreaolivato/TikTok-LoginKit-PHP#13]
I reviewed the developers page. After running into problems to get the follower-count and follows-count, I do some test.
Can it be, that the LoginKit need´s all three scopes of user.* to running correct?
I added the last possible sope to my app (user.info.profile). Hope it will be approved.

Actually I only added user.info.basic and user.info.stats to get the followers.

![image](https://github.com/andreaolivato/TikTok-LoginKit-PHP/assets/4928271/f4716044-5626-4a6c-b693-034a4b7e6e54)

I will report, if it works with all three possible scopes.

**Comment by andreaolivato** [comment]
The additional permission is not required. You only need the stats.

See the reply on the other issue you had opened.
