### ISSUE TITLE
Class "gimucco\TikTokLoginKit" not found

### ISSUE THREAD

**Issue by ley-288** [andreaolivato/TikTok-LoginKit-PHP#2]
I believe composer installed package correctly.

<img width="1197" alt="Screenshot 2022-04-14 at 12 07 55" src="https://user-images.githubusercontent.com/67469616/163364054-d9243f1d-fcc9-4975-a755-73fc17cfb706.png">

**Comment by ley-288** [comment]
Using the .ini method works

**Comment by andreaolivato** [comment]
The example in the readme was outdated.

Please try 

`$_TK = new TikTokLoginKit\Connector($api_key, $api_secret, $redirect_uri);`

Let me know if it works, I will update the readme

**Comment by ley-288** [comment]
Works and thank you!
