### ISSUE TITLE
Undefined property stdClass::$video_list

### ISSUE THREAD

**Issue by ley-288** [andreaolivato/TikTok-LoginKit-PHP#3]
Hi this package is really helpful thank you! but im having a few small problems.
A request for video list permissions is not sent, not sure if that is the package because i requested the permission in tiktok dev.
Only avatar and display name.

<img width="399" alt="Screenshot 2022-04-15 at 13 52 23" src="https://user-images.githubusercontent.com/67469616/163567823-ce68ec50-a4cd-4d34-acdb-a65f1d45454f.png">

**Comment by andreaolivato** [comment]
When you use the `getRedirect` function, did you pass the list of permissions, including PERMISSION_VIDEO_LIST?

**Comment by ley-288** [comment]
Oh lord, No i didnt add it in function, so stupid! thank you!! 🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️
