### ISSUE TITLE
Update to OAuth2 

### ISSUE THREAD

**Issue by DevLoris** [andreaolivato/TikTok-LoginKit-PHP#5]
Tiktok is planning to remove v1 soon

Need an update to OAuth2

[https://developers.tiktok.com/bulletin/migration-guidance-oauth-v1/](https://developers.tiktok.com/bulletin/migration-guidance-oauth-v1/)

**Comment by andreaolivato** [comment]
The new v0.5 implements the new TikTok protocols. Feel free to test and let me know if you find any issues with the upgrade

**Comment by DevLoris** [comment]
Hello i test it tomorrow ! Thanks
