### ISSUE TITLE
Getting error everything did correct

### ISSUE THREAD

**Issue by MirShaon** [andreaolivato/TikTok-LoginKit-PHP#6]
My app on Staging 

Everything did correct when i run the library  showing the button [Log in with TikTok] but i did click on it it show below error  if anyone already solved the issue please answer 

Something went wrong

We couldn't log in with TikTok. This may be due to specific app settings.

If you're a developer, correct the following and try again:

redirect_uri
Refer to our [Developer Documentation](https://developers.tiktok.com/doc) for more information.

TIA

**Comment by andreaolivato** [comment]
Hi there,

It seems like your redirect_uri was not set correctly on your Developer settings.

Make sure that you set the redirect_uri in your TikTok developer account to the same value you pass to the library. They need to match exactly.

Please note you need to set the "Redirect URI" parameters, not the "Redirect domain" which is deprecated.

**Comment by MirShaon** [comment]
I used the exactly same redirect_uri as on my titktok app and code and i passed same 
Yes i did used Redirect URI not Redirect domain but same error. is because my app is on staging? or once my app on live mode it will start working?

**Comment by andreaolivato** [comment]
Until your app is approved from TikTok with all permissions you asked for, it will not work.
