### ISSUE TITLE
Typo in CreatorQuery->getTokenType() to get max_video_duration_sec

### ISSUE THREAD

**Issue by claudeschneider** [andreaolivato/TikTok-LoginKit-PHP#7]
I was trying to get `max_video_duration_sec` for a creator, and I couldn't find a getter for this variable.

I found it named `getTokenType()`

Looks like a copy/paste typo where the getter wasn't named correctly.

src/response/CreatorQuery.php
`getTokenType()` should be renamed to `getMaxVideoDuration()`

**Comment by andreaolivato** [comment]
Thanks for the report! I confirm it's been fixed. It's already in prod, v0.6.4
