### ISSUE TITLE
Missing brand_content_toggle and brand_organic_toggle

### ISSUE THREAD

**Issue by claudeschneider** [andreaolivato/TikTok-LoginKit-PHP#8]
Thanks for the recent typo fix in 0.6.4

I just noticed 2 more properties are missing from Connector.php->publishVideoFromURL()

https://developers.tiktok.com/doc/content-posting-api-reference-direct-post/
- brand_content_toggle | bool | Set to true if the video is a paid partnership to promote a third-party business.
- brand_organic_toggle | bool | Set to true if this video is promoting the creator's own business.

**Comment by andreaolivato** [comment]
Thanks for the feedback. I confirm it's been released in v0.6.5
